fn = input('Enter name: ')
ln = input('Enter last name: ')
cn = input('Enter city name: ')
pn = input('Enter phone number: ')
ei = input('Enter email id: ')
print('-------------------------------------')
print('First name :',fn)
print('Last name :',ln)
print('City name :',cn)
print('Phone number :',pn)
print('Email id :',ei)
